package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Caddie generated by hbm2java
 */
@Entity
@Table(name = "caddie", catalog = "billeterie")
public class Caddie implements java.io.Serializable {

    private int caddieId;
    private int userId;

    public Caddie() {
    }

    public Caddie(int caddieId, int userId) {
        this.caddieId = caddieId;
        this.userId = userId;
    }

    @Id
    @Column(name = "caddie_id", unique = true, nullable = false)
    public int getCaddieId() {
        return this.caddieId;
    }

    public void setCaddieId(int caddieId) {
        this.caddieId = caddieId;
    }

    @Column(name = "user_id", nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}
