package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Film generated by hbm2java
 */
@Entity
@Table(name="film"
    ,catalog="billeterie"
)
public class Film  implements java.io.Serializable {


     private int filmId;
     private String titre;
     private String resume;

    public Film() {
    }

	
    public Film(int filmId, String titre) {
        this.filmId = filmId;
        this.titre = titre;
    }
    public Film(int filmId, String titre, String resume) {
       this.filmId = filmId;
       this.titre = titre;
       this.resume = resume;
    }
   
     @Id 
    
    @Column(name="Film_id", unique=true, nullable=false)
    public int getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }
    
    @Column(name="titre", nullable=false)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    
    @Column(name="resume")
    public String getResume() {
        return this.resume;
    }
    
    public void setResume(String resume) {
        this.resume = resume;
    }




}


