package com.epita.bean;
// Generated May 17, 2012 11:20:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Film generated by hbm2java
 */
@Entity
@Table(name="FILM"
    ,catalog="Billeterie"
)
public class Film  implements java.io.Serializable {


     private Integer filmId;
     private String titre;
     private String resume;
     private Set seanceses = new HashSet(0);

    public Film() {
    }

	
    public Film(String titre) {
        this.titre = titre;
    }
    public Film(String titre, String resume, Set seanceses) {
       this.titre = titre;
       this.resume = resume;
       this.seanceses = seanceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Film_id", unique=true, nullable=false)
    public Integer getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }
    
    @Column(name="titre", nullable=false)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    
    @Column(name="resume")
    public String getResume() {
        return this.resume;
    }
    
    public void setResume(String resume) {
        this.resume = resume;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="film")
    public Set getSeanceses() {
        return this.seanceses;
    }
    
    public void setSeanceses(Set seanceses) {
        this.seanceses = seanceses;
    }




}


