package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservationId generated by hbm2java
 */
@Embeddable
public class ReservationId  implements java.io.Serializable {


     private int reservationId;
     private int commandeId;

    public ReservationId() {
    }

    public ReservationId(int reservationId, int commandeId) {
       this.reservationId = reservationId;
       this.commandeId = commandeId;
    }
   

    @Column(name="reservation_id", nullable=false)
    public int getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }

    @Column(name="commande_id", nullable=false)
    public int getCommandeId() {
        return this.commandeId;
    }
    
    public void setCommandeId(int commandeId) {
        this.commandeId = commandeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservationId) ) return false;
		 ReservationId castOther = ( ReservationId ) other; 
         
		 return (this.getReservationId()==castOther.getReservationId())
 && (this.getCommandeId()==castOther.getCommandeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getReservationId();
         result = 37 * result + this.getCommandeId();
         return result;
   }   


}


