package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="billeterie"
)
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private int seanceId;
     private int userId;
     private int caddieId;

    public Reservation() {
    }

    public Reservation(ReservationId id, int seanceId, int userId, int caddieId) {
       this.id = id;
       this.seanceId = seanceId;
       this.userId = userId;
       this.caddieId = caddieId;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="reservationId", column=@Column(name="reservation_id", nullable=false) ), 
        @AttributeOverride(name="commandeId", column=@Column(name="commande_id", nullable=false) ) } )
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    
    @Column(name="Seance_id", nullable=false)
    public int getSeanceId() {
        return this.seanceId;
    }
    
    public void setSeanceId(int seanceId) {
        this.seanceId = seanceId;
    }
    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="caddie_id", nullable=false)
    public int getCaddieId() {
        return this.caddieId;
    }
    
    public void setCaddieId(int caddieId) {
        this.caddieId = caddieId;
    }




}


