package com.epita.bean;
// Generated May 17, 2012 11:20:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="USER"
    ,catalog="Billeterie"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private String login;
     private String nom;
     private String prenom;
     private String adresse;
     private String cdp;
     private String ville;
     private String email;
     private boolean admin;
     private String password;
     private Set commandes = new HashSet(0);
     private Set reservations = new HashSet(0);

    public User() {
    }

	
    public User(String login, String nom, String prenom, boolean admin, String password) {
        this.login = login;
        this.nom = nom;
        this.prenom = prenom;
        this.admin = admin;
        this.password = password;
    }
    public User(String login, String nom, String prenom, String adresse, String cdp, String ville, String email, boolean admin, String password, Set commandes, Set reservations) {
       this.login = login;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.cdp = cdp;
       this.ville = ville;
       this.email = email;
       this.admin = admin;
       this.password = password;
       this.commandes = commandes;
       this.reservations = reservations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="login", nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="nom", nullable=false, length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @Column(name="prenom", nullable=false, length=45)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    
    @Column(name="adresse", length=45)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    @Column(name="cdp", length=45)
    public String getCdp() {
        return this.cdp;
    }
    
    public void setCdp(String cdp) {
        this.cdp = cdp;
    }
    
    @Column(name="ville", length=45)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="admin", nullable=false)
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="user")
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="user")
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


