package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommamdeEtat generated by hbm2java
 */
@Entity
@Table(name = "commamde_etat", catalog = "billeterie")
public class CommamdeEtat implements java.io.Serializable {

    private int commandeEtatId;
    private String libele;

    public CommamdeEtat() {
    }

    public CommamdeEtat(int commandeEtatId) {
        this.commandeEtatId = commandeEtatId;
    }

    public CommamdeEtat(int commandeEtatId, String libele) {
        this.commandeEtatId = commandeEtatId;
        this.libele = libele;
    }

    @Id
    @Column(name = "COMMANDE_ETAT_ID", unique = true, nullable = false)
    public int getCommandeEtatId() {
        return this.commandeEtatId;
    }

    public void setCommandeEtatId(int commandeEtatId) {
        this.commandeEtatId = commandeEtatId;
    }

    @Column(name = "libele", length = 45)
    public String getLibele() {
        return this.libele;
    }

    public void setLibele(String libele) {
        this.libele = libele;
    }
}
