package com.epita.bean;
// Generated May 17, 2012 11:20:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name="COMMANDE"
    ,catalog="Billeterie"
)
public class Commande  implements java.io.Serializable {


     private Integer commandeId;
     private User user;
     private CommamdeEtat commamdeEtat;
     private Set reservations = new HashSet(0);

    public Commande() {
    }

	
    public Commande(User user, CommamdeEtat commamdeEtat) {
        this.user = user;
        this.commamdeEtat = commamdeEtat;
    }
    public Commande(User user, CommamdeEtat commamdeEtat, Set reservations) {
       this.user = user;
       this.commamdeEtat = commamdeEtat;
       this.reservations = reservations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="commande_id", unique=true, nullable=false)
    public Integer getCommandeId() {
        return this.commandeId;
    }
    
    public void setCommandeId(Integer commandeId) {
        this.commandeId = commandeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMMANDE_ETAT_ID", nullable=false)
    public CommamdeEtat getCommamdeEtat() {
        return this.commamdeEtat;
    }
    
    public void setCommamdeEtat(CommamdeEtat commamdeEtat) {
        this.commamdeEtat = commamdeEtat;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="commande")
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


