package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name="commande"
    ,catalog="billeterie"
)
public class Commande  implements java.io.Serializable {


     private int commandeId;
     private int userId;
     private int commandeEtatId;

    public Commande() {
    }

    public Commande(int commandeId, int userId, int commandeEtatId) {
       this.commandeId = commandeId;
       this.userId = userId;
       this.commandeEtatId = commandeEtatId;
    }
   
     @Id 
    
    @Column(name="commande_id", unique=true, nullable=false)
    public int getCommandeId() {
        return this.commandeId;
    }
    
    public void setCommandeId(int commandeId) {
        this.commandeId = commandeId;
    }
    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="COMMANDE_ETAT_ID", nullable=false)
    public int getCommandeEtatId() {
        return this.commandeEtatId;
    }
    
    public void setCommandeEtatId(int commandeEtatId) {
        this.commandeEtatId = commandeEtatId;
    }




}


