package com.epita.bean;
// Generated May 12, 2012 12:34:39 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seances generated by hbm2java
 */
@Entity
@Table(name="seances"
    ,catalog="billeterie"
)
public class Seances  implements java.io.Serializable {


     private int seanceId;
     private int filmId;
     private Date date;
     private double prix;
     private String cinema;
     private String addresse;

    public Seances() {
    }

	
    public Seances(int seanceId, int filmId, Date date, double prix, String cinema) {
        this.seanceId = seanceId;
        this.filmId = filmId;
        this.date = date;
        this.prix = prix;
        this.cinema = cinema;
    }
    public Seances(int seanceId, int filmId, Date date, double prix, String cinema, String addresse) {
       this.seanceId = seanceId;
       this.filmId = filmId;
       this.date = date;
       this.prix = prix;
       this.cinema = cinema;
       this.addresse = addresse;
    }
   
     @Id 
    
    @Column(name="Seance_id", unique=true, nullable=false)
    public int getSeanceId() {
        return this.seanceId;
    }
    
    public void setSeanceId(int seanceId) {
        this.seanceId = seanceId;
    }
    
    @Column(name="Film_id", nullable=false)
    public int getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="prix", nullable=false, precision=22, scale=0)
    public double getPrix() {
        return this.prix;
    }
    
    public void setPrix(double prix) {
        this.prix = prix;
    }
    
    @Column(name="cinema", nullable=false, length=45)
    public String getCinema() {
        return this.cinema;
    }
    
    public void setCinema(String cinema) {
        this.cinema = cinema;
    }
    
    @Column(name="addresse", length=45)
    public String getAddresse() {
        return this.addresse;
    }
    
    public void setAddresse(String addresse) {
        this.addresse = addresse;
    }




}


