package com.epita.bean;
// Generated May 17, 2012 11:20:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seances generated by hbm2java
 */
@Entity
@Table(name="SEANCES"
    ,catalog="Billeterie"
)
public class Seances  implements java.io.Serializable {


     private Integer seanceId;
     private Film film;
     private Date date;
     private double prix;
     private String cinema;
     private String addresse;
     private Set reservations = new HashSet(0);

    public Seances() {
    }

	
    public Seances(Film film, Date date, double prix, String cinema) {
        this.film = film;
        this.date = date;
        this.prix = prix;
        this.cinema = cinema;
    }
    public Seances(Film film, Date date, double prix, String cinema, String addresse, Set reservations) {
       this.film = film;
       this.date = date;
       this.prix = prix;
       this.cinema = cinema;
       this.addresse = addresse;
       this.reservations = reservations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Seance_id", unique=true, nullable=false)
    public Integer getSeanceId() {
        return this.seanceId;
    }
    
    public void setSeanceId(Integer seanceId) {
        this.seanceId = seanceId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Film_id", nullable=false)
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="prix", nullable=false, precision=22, scale=0)
    public double getPrix() {
        return this.prix;
    }
    
    public void setPrix(double prix) {
        this.prix = prix;
    }
    
    @Column(name="cinema", nullable=false, length=45)
    public String getCinema() {
        return this.cinema;
    }
    
    public void setCinema(String cinema) {
        this.cinema = cinema;
    }
    
    @Column(name="addresse", length=45)
    public String getAddresse() {
        return this.addresse;
    }
    
    public void setAddresse(String addresse) {
        this.addresse = addresse;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="seances")
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


